In [22]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)
print(type(arr))

[1 2 3 4]
1
<class 'numpy.ndarray'>


In [19]:
import numpy as np
arr=np.array(43)
print(arr)
print(arr.ndim)

43
0


In [29]:
import numpy as np
arr=np.array([[43,87,97,9]])
print(arr)
print(arr.ndim)


[[43 87 97  9]]
2


In [28]:
import numpy as np
arr=np.array([[[6,0,7,43,9,97]]])
print(arr)
print(arr.ndim)
print(arr[0])


[[[ 6  0  7 43  9 97]]]
3
[[ 6  0  7 43  9 97]]


In [35]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st row",arr[0,1])
print("3rd elemnet of 1st row",arr[0,2])
print("3rd element of 2nd row",arr[1,2])

2nd element on 1st row 2
3rd elemnet of 1st row 3
3rd element of 2nd row 8


In [64]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,0,2])
print(arr[0,1,2])
print(arr[1,0,2])
print(arr[1,1,2])
print("addition is:",arr[0,0,2]+arr[0,1,2]+arr[1,0,2]+arr[1,1,2])

3
6
9
12
addition is: 30


In [65]:
import numpy as np
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print("3rd element of second array of first array is:",arr[0,1,2])
print(arr[0,1,2])
print(arr[1,1,-1])

3rd element of second array of first array is: 8
8
20
